import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:durus/core/durus_api.dart';
import 'package:durus/core/utils.dart';
import 'package:durus/l10n/app_localizations.dart';
import 'package:durus/l10n/l10n_ext.dart';
import 'package:durus/models/models.dart';
import 'package:durus/providers/providers.dart';
import 'package:durus/widgets/widgets.dart';

/// Teacher/manager notifications center.
///
/// Rows are generated by DB triggers (attendance, notes, tests, fees,
/// payments, announcements, teacher join). Tapping an unread row marks it
/// read; the app bar action marks every row read.
class NotificationsScreen extends ConsumerStatefulWidget {
  const NotificationsScreen({super.key});

  @override
  ConsumerState<NotificationsScreen> createState() =>
      _NotificationsScreenState();
}

class _NotificationsScreenState extends ConsumerState<NotificationsScreen> {
  String _selectedType = 'all';

  /// Pending delayed deletes keyed by notification id. The row is removed
  /// from the server only when its timer fires, so the undo snackbar can
  /// still rescue it — client-side rows can't be re-created (server-owned).
  final Map<String, Timer> _pendingDeletes = {};

  @override
  void dispose() {
    for (final timer in _pendingDeletes.values) {
      timer.cancel();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final notificationsAsync = ref.watch(teacherNotificationsProvider);
    final prefsAsync = ref.watch(notificationPrefsProvider);
    final api = ref.read(apiProvider);

    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.notificationsTitle),
        actions: [
          TextButton(
            onPressed: () async {
              final items =
                  notificationsAsync.valueOrNull ?? const <AppNotification>[];
              await _markAllRead(ref, api, items);
            },
            child: Text(l10n.notificationsMarkAll),
          ),
        ],
      ),
      body: notificationsAsync.when(
        loading: () => const LoadingView(),
        error: (_, _) => ErrorRetry(
          message: l10n.commonError,
          onRetry: () => ref.invalidate(teacherNotificationsProvider),
        ),
        data: (allItems) {
          if (allItems.isEmpty) {
            return EmptyState(
              icon: Icons.notifications_off_outlined,
              message: l10n.notificationsEmpty,
            );
          }
          final prefs = prefsAsync.valueOrNull ?? {};
          final visible = allItems.where((n) => prefs[n.type] ?? true).toList();
          final types = <String>{'all'};
          for (final n in visible) {
            types.add(n.type);
          }
          final filtered = _selectedType == 'all'
              ? visible
              : visible.where((n) => n.type == _selectedType).toList();

          return Column(
            children: [
              // --- Filter chips ---
              if (types.length > 1)
                SizedBox(
                  height: 52,
                  child: ListView(
                    scrollDirection: Axis.horizontal,
                    padding: const EdgeInsets.symmetric(
                      horizontal: 12,
                      vertical: 8,
                    ),
                    children: [
                      _FilterChip(
                        label: l10n.notificationsCategoryAll,
                        selected: _selectedType == 'all',
                        onTap: () => setState(() => _selectedType = 'all'),
                      ),
                      for (final type in types.where((t) => t != 'all'))
                        _FilterChip(
                          label: _typeLabel(l10n, type),
                          selected: _selectedType == type,
                          onTap: () => setState(() => _selectedType = type),
                        ),
                    ],
                  ),
                ),
              // --- Notification list ---
              Expanded(
                child: RefreshIndicator(
                  onRefresh: () async =>
                      ref.invalidate(teacherNotificationsProvider),
                  child: ListView.builder(
                    physics: const AlwaysScrollableScrollPhysics(),
                    padding: const EdgeInsets.symmetric(
                      horizontal: 12,
                      vertical: 8,
                    ),
                    itemCount: filtered.length,
                    itemBuilder: (context, index) {
                      final item = filtered[index];
                      return _NotificationCard(
                        notification: item,
                        onTap: () => _markRead(ref, api, item),
                        onDelete: () => _delete(ref, api, item),
                        onMarkRead: () => _markRead(ref, api, item),
                      );
                    },
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );
  }

  String _typeLabel(AppLocalizations l10n, String type) {
    return switch (type) {
      'general' => l10n.notificationsCategoryGeneral,
      'attendance' => l10n.notificationsCategoryAttendance,
      'note' => l10n.notificationsCategoryAttendance,
      'test' => l10n.notificationsCategoryTests,
      'fee' => l10n.notificationsCategoryFees,
      'payment' => l10n.notificationsCategoryFees,
      'announcement' => l10n.notificationsCategoryAnnouncements,
      'teacher' => l10n.notificationsCategoryGeneral,
      'session_change' => l10n.notificationsCategoryAttendance,
      'absence_excuse' => l10n.notificationsCategoryAttendance,
      _ => type,
    };
  }

  Future<void> _markAllRead(
    WidgetRef ref,
    DurusApi api,
    List<AppNotification> items,
  ) async {
    if (items.isEmpty) return;
    await api.markTeacherNotificationsRead([for (final n in items) n.id]);
    ref.invalidate(teacherNotificationsProvider);
  }

  Future<void> _markRead(
    WidgetRef ref,
    DurusApi api,
    AppNotification item,
  ) async {
    if (item.isRead) return;
    await api.markTeacherNotificationsRead([item.id]);
    ref.invalidate(teacherNotificationsProvider);
  }

  Future<void> _delete(
    WidgetRef ref,
    DurusApi api,
    AppNotification item,
  ) async {
    final l10n = context.l10n;
    _pendingDeletes[item.id]?.cancel();
    _pendingDeletes[item.id] = Timer(const Duration(seconds: 4), () async {
      _pendingDeletes.remove(item.id);
      try {
        await api.deleteTeacherNotification(item.id);
        ref.invalidate(teacherNotificationsProvider);
      } catch (_) {
        // Delete failed: the row stays, next refresh restores it.
      }
    });
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(l10n.notificationsDeleted),
        duration: const Duration(seconds: 4),
        action: SnackBarAction(
          label: l10n.commonUndo,
          onPressed: () {
            _pendingDeletes.remove(item.id)?.cancel();
            if (mounted) {
              ScaffoldMessenger.of(context).hideCurrentSnackBar();
            }
          },
        ),
      ),
    );
  }
}

class _FilterChip extends StatelessWidget {
  const _FilterChip({
    required this.label,
    required this.selected,
    required this.onTap,
  });

  final String label;
  final bool selected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Padding(
      padding: const EdgeInsets.only(right: 8),
      child: GestureDetector(
        onTap: onTap,
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 200),
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 6),
          decoration: BoxDecoration(
            color: selected
                ? scheme.primaryContainer
                : scheme.surfaceContainerHigh.withValues(alpha: 0.5),
            borderRadius: BorderRadius.circular(999),
            border: Border.all(
              color: selected
                  ? scheme.primary.withValues(alpha: 0.6)
                  : scheme.outlineVariant.withValues(alpha: 0.4),
            ),
          ),
          child: Text(
            label,
            style: theme.textTheme.labelMedium?.copyWith(
              color: selected ? scheme.onPrimaryContainer : scheme.onSurfaceVariant,
              fontWeight: selected ? FontWeight.w600 : FontWeight.normal,
            ),
          ),
        ),
      ),
    );
  }
}

class _NotificationCard extends StatelessWidget {
  const _NotificationCard({
    required this.notification,
    required this.onTap,
    required this.onDelete,
    required this.onMarkRead,
  });

  final AppNotification notification;
  final VoidCallback onTap;
  final VoidCallback onDelete;
  final VoidCallback onMarkRead;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final n = notification;
    final unread = !n.isRead;
    final body = n.body;
    final createdAt = n.createdAt;

    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      clipBehavior: Clip.antiAlias,
      child: InkWell(
        onTap: onTap,
        child: Padding(
          padding: const EdgeInsets.all(12),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Padding(
                padding: const EdgeInsets.only(top: 6),
                child: Container(
                  width: 12,
                  height: 12,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: unread ? scheme.primary : Colors.transparent,
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      n.title,
                      style: theme.textTheme.bodyLarge?.copyWith(
                        fontWeight:
                            unread ? FontWeight.bold : FontWeight.normal,
                      ),
                    ),
                    if (body != null && body.isNotEmpty) ...[
                      const SizedBox(height: 4),
                      Text(body, style: theme.textTheme.bodyMedium),
                    ],
                    const SizedBox(height: 6),
                    Row(
                      children: [
                        if (unread)
                          StatusChip(
                            label: l10n.notificationsUnreadCount,
                            color: scheme.tertiaryContainer,
                          ),
                        if (createdAt != null) ...[
                          if (unread) const SizedBox(width: 8),
                          Text(
                            fmtDate(createdAt),
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: scheme.onSurfaceVariant,
                            ),
                          ),
                        ],
                      ],
                    ),
                  ],
                ),
              ),
              PopupMenuButton<String>(
                onSelected: (action) {
                  switch (action) {
                    case 'read':
                      onMarkRead();
                    case 'delete':
                      onDelete();
                  }
                },
                itemBuilder: (_) => [
                  if (unread)
                    PopupMenuItem(
                      value: 'read',
                      child: Text(l10n.notificationsMarkRead),
                    ),
                  PopupMenuItem(
                    value: 'delete',
                    child: Text(
                      l10n.commonDelete,
                      style: TextStyle(color: scheme.error),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
