import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:durus/core/durus_api.dart';
import 'package:durus/core/utils.dart';
import 'package:durus/l10n/l10n_ext.dart';
import 'package:durus/models/models.dart';
import 'package:durus/providers/providers.dart';
import 'package:durus/widgets/widgets.dart';

/// Teacher/manager notifications center.
///
/// Rows are generated by DB triggers (attendance, notes, tests, fees,
/// payments, announcements, teacher join). Tapping an unread row marks it
/// read; the app bar action marks every row read.
class NotificationsScreen extends ConsumerWidget {
  const NotificationsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l10n = context.l10n;
    final notifications = ref.watch(teacherNotificationsProvider);
    final api = ref.read(apiProvider);

    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.notificationsTitle),
        actions: [
          TextButton(
            onPressed: () async {
              final items =
                  notifications.valueOrNull ?? const <AppNotification>[];
              await _markAllRead(ref, api, items);
            },
            child: Text(l10n.notificationsMarkAll),
          ),
        ],
      ),
      body: notifications.when(
        loading: () => const LoadingView(),
        error: (_, _) => ErrorRetry(
          message: l10n.commonError,
          onRetry: () => ref.invalidate(teacherNotificationsProvider),
        ),
        data: (items) {
          if (items.isEmpty) {
            return EmptyState(
              icon: Icons.notifications_off_outlined,
              message: l10n.notificationsEmpty,
            );
          }
          return RefreshIndicator(
            onRefresh: () async {
              ref.invalidate(teacherNotificationsProvider);
            },
            child: ListView.builder(
              physics: const AlwaysScrollableScrollPhysics(),
              padding: const EdgeInsets.all(16),
              itemCount: items.length,
              itemBuilder: (context, index) {
                final item = items[index];
                return _NotificationCard(
                  notification: item,
                  onTap: () async {
                    await _markRead(ref, api, item);
                  },
                );
              },
            ),
          );
        },
      ),
    );
  }

  Future<void> _markAllRead(
    WidgetRef ref,
    DurusApi api,
    List<AppNotification> items,
  ) async {
    if (items.isEmpty) return;
    await api.markTeacherNotificationsRead([for (final n in items) n.id]);
    ref.invalidate(teacherNotificationsProvider);
  }

  Future<void> _markRead(
    WidgetRef ref,
    DurusApi api,
    AppNotification item,
  ) async {
    await api.markTeacherNotificationsRead([item.id]);
    ref.invalidate(teacherNotificationsProvider);
  }
}

class _NotificationCard extends StatelessWidget {
  const _NotificationCard({required this.notification, required this.onTap});

  final AppNotification notification;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final n = notification;
    final unread = !n.isRead;
    final body = n.body;
    final createdAt = n.createdAt;

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      clipBehavior: Clip.antiAlias,
      child: InkWell(
        onTap: onTap,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Padding(
                padding: const EdgeInsets.only(top: 6),
                child: Container(
                  width: 12,
                  height: 12,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: unread ? scheme.primary : Colors.transparent,
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      n.title,
                      style: theme.textTheme.bodyLarge?.copyWith(
                        fontWeight:
                            unread ? FontWeight.bold : FontWeight.normal,
                      ),
                    ),
                    if (body != null && body.isNotEmpty) ...[
                      const SizedBox(height: 4),
                      Text(body, style: theme.textTheme.bodyMedium),
                    ],
                    const SizedBox(height: 8),
                    Wrap(
                      spacing: 8,
                      runSpacing: 4,
                      crossAxisAlignment: WrapCrossAlignment.center,
                      children: [
                        if (unread)
                          StatusChip(
                            label: l10n.notificationsUnreadCount,
                            color: scheme.tertiaryContainer,
                          ),
                        if (createdAt != null)
                          Text(
                            fmtDate(createdAt),
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: scheme.onSurfaceVariant,
                            ),
                          ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}